/*

 MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : menutiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menumapWidth 20
#define menumapHeight 18
#define menumapBank 0

extern unsigned char menumap[];

/* End of MENUMAP.H */
